### PR TITLE
Feat navbar component

### PR DESCRIPTION
**Pull request by omarouhra**

### CODE REVIEW

**Review by amine-omari — COMMENTED** [review]
@omarouhra

**Review by amine-omari — COMMENTED** [review]
@omarouhra

**Review by amine-omari — COMMENTED** [review]
@omarouhra

**Review by amine-omari — COMMENTED** [review]
@omarouhra

**Comment by omarouhra** [comment]
@AMINEomari  Amazing work bro! you can merge this branch

the code is clean! keep up the good work 🚀 🚀

**Comment by omarouhra** [comment]
@AMINEomari  one thing i would suggest is to deploy the app to vercel 👍

**Comment by omarouhra** [comment]
@AMINEomari  You can start working ok the nav topbar 👍

**Pull request merged**
